### ISSUE TITLE
API Bridge - Time Offset

### ISSUE THREAD

**Issue by radiorob** [openbroadcaster/drupal-broadcast-media#1]
Create a simple offset, in GUI API Bridge Module to provide a way to have schedule information display on front end Drupal site where the originating station is located in a different time zone.  

For example, we have a station with playout box located in Nunavut and the managing server is located in Ottawa.  The server is set for local time in Ottawa and displays the schedule incorrectly where the Nunavut station is 2 hours different on Mountain Time.

**Comment by transistorfet** [comment]
Finally managed to track this down.  Drupal has a setting to set the default timezone, under Regional Settings, however it will not apply to the cron job if the "Users may set their own timezone" option is checked.  If you uncheck that option, the the cron job which fetches the schedules through the api will use the drupal timezone, which can be set to match the player's timezone.  This would also keep all the times used on the drupal website consistent.
